OVC_IMS/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ovc_main.views import dashboard_views
from rapidsms.backends.kannel.views import KannelBackendView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'ovc_home.views.ovc_login', name='ovc_login'),
    url(r'^change_password/', 'ovc_home.views.change_password', name='change_password'),
    url(r'^logout/', 'ovc_home.views.ovc_logout', name='ovc_logout'),
    url(r'^allocate_role/', 'ovc_home.views.allocate_role', name='allocate_role'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^home/', include('ovc_home.urls')),
    url(r'^organisation/', include('ovc_main.urls')),
    url(r'^workforce/', include('ovc_main.urls')),
    url(r'^beneficiary/', include('ovc_main.urls')),
    url(r'^capture/', include('ovc_main.urls')),
    url(r'^api/', include('ovc_main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', dashboard_views.report_counts, name='report_counts'),
    url(r'^dashboard_children/', dashboard_views.dashboard_children, name='dashboard_children'),
    url(r'^test/', dashboard_views.test, name='test'),
    #intervention, activities, service, forms
    url(r'^forms/', include('ovc_main.urls')),
    url(r'^reports/', include('ovc_main.urls')),
    #RapidSMS
    url(r'^sms/', include('ovc_sms.urls')),
    url(r'^library/', include('ovc_library.urls')),
    url(r'^kannel/', KannelBackendView.as_view(backend_name="airtel")),

)

ovc_main/urls.py
'''
Created on Sep 2, 2014

@author: MLumpa
'''
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from ovc_main.views import reg_views as views, \
    service_views, api_views as api, \
    upload_download_views as capture_views, \
    captureapp
from OVC_IMS import settings

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^new/', views.new_organisation, name='new-organisation'),
    url(r'^wards/', views.listofwards, name='listofwards'),
    url(r'^orglists/', views.org_search_results, name='org_search_results'),
    url(r'^view_org/', views.organisation_view, name='organisation_view'),
    url(r'^update_org/', views.update_organisation, name='organisation_update'),
    url(r'^wfcsearch/', views.workforce_index, name='wfc_search_index'),
    url(r'^wfclists/', views.wfc_search_results, name='wfc_search_index'),
    url(r'^get_workforce_for_res_institution/', views.get_workforce_for_res_institution, name='get_workforce_for_res_institution'),
    url(r'^new_workforce/', views.new_workforce, name='workforce'),
    url(r'^orgautocomp/', views.org_autocompletion_list, name='orgautocomplete'),
    url(r'^res_wfc_autocomplete/', views.res_wfc_autocomplete, name='res_institute_wfc_autocomplete'),
    url(r'^workforce_training_autocomplete/', views.all_workforce_autocomplete, name='workforce_training_autocomplete'),
    url(r'^res_child_autocomplete/', views.res_child_autocomplete, name='res_child_autocomplete'), 
    url(r'^public_sens_ben_autocomp/', views.public_sens_ben_autocomp, name='public_sens_ben_autocomp'),      
    url(r'^view_wfc/', views.workforce_view, name='workforce_view'),
    url(r'^update_wfc/', views.workforce_update, name='workforce_update'),
    url(r'^communities/', views.list_of_cwacs_in_ward, name='list_of_cwacs_in_ward'),
    url(r'^ben_search/', views.search_beneficiary, name='ben_search'),
    url(r'^guardian/', views.new_guardian_reg, name='guardian'),
    url(r'^child/', views.new_child_reg, name='child'),
    url(r'^ben_autocomplete/', views.ben_autocompletion_list, name='benautocomplete'),
    url(r'^ben_wfc_autocomplete/', views.ben_wfc_autocompletion_list, name='benwfcautocomplete'),
    url(r'^ben_res_autocomplete/', views.ben_res_autocompletion_list, name='benresautocomplete'),
    url(r'^benlists/', views.ben_search_results, name='ben_search_results'),
    url(r'^formlists/', views.form_search_results, name='form_search_results'),
    url(r'^view_ben/', views.beneficiary_view, name='beneficiary_view'),
    url(r'^update_ben/', views.update_beneficiary, name='beneficiary_update'),
    url(r'^guardian_contact/', views.get_guardian_contacts, name='guard_contact'),
    url(r'^capture_admin/', capture_views.capture_admin, name='capture_administration'),
    url(r'^begin_upload/', capture_views.start_upload, name='start_upload'),
    url(r'^begin_download/', capture_views.start_download, name='start_download'),
    url(r'^stop_download_upload/', capture_views.stop_download_upload, name='stop_download_upload'),
    url(r'^upload/', api.process_upload, name='api_capture_upload'),
    url(r'^download/', api.download, name='download_sections'),
    #url(r'^data_dictionary/', api.data_dictionary, name='data_dictionary'),
    url(r'^check_names/', views.check_person_names, name='check_names'),
    url(r'^check_form_titles/', views.check_form_titles, name='check_form_titles'),
    url(r'^refresh_capture_site/', capture_views.refresh_capture_site, name='refresh_capture_site'),
    url(r'^forms_home/', views.forms_home_page, name='forms_home'),
    url(r'^subject/', views.get_subject, name='subject'),
    url(r'^add_form/', views.load_form, name='add_form'),
    #url(r'^user_can_add_form/', views.user_can_add_form, name='user_can_add_form'),
    url(r'^get_wfc_object/', views.get_wfc, name='get_wfc_object'),
    url(r'^delete/', views.delete_form, name='delete'),
    url(r'^reports_and_analysis/', views.reports_and_analysis, name='reports_and_analysis'),
    url(r'^rep_utils/', views.report_utils, name='rep_utils'),
    url(r'^report_params/', views.report_paramenters, name='report_params'),
    url(r'^run_report/', views.get_report, name='run_report'),
    #url(r'^persons/', views.get_persons_list, name='api_persons_list'),
    url(r'^get_reported_by_options/', views.get_reported_by_options, name='get_field_options'),
    url(r'^help/', views.view_help, name='help'),
    url(r'^form-search/', service_views.forms_search, name='form_search'),
    url(r'^delrecord/', service_views.delete_form, name='delete_form'),
    #url(r'^help/', TemplateView.as_view(template_name='ovc_main/ZOMIS_help_html/HTML/index.html')),
    
    url(r'^basic_service_referral/', service_views.basic_service_referral_vw, name='basic_service_referral'),
    url(r'^residential_institution/', service_views.residential_institution_vw, name='residential_institution'),
    url(r'^workforce_training/', service_views.workforce_training_vw, name='workforce_training'),
    url(r'^public_sensitisation/', service_views.public_sensitisation_vw, name='public_sensitisation'),
    url(r'^all_ben_autocomplete/', service_views.beneficiary_search_result, name='beneficiary_search_result'),
    
    url(r'^initialsitesetup/', captureapp.setup_capture_site, name='capturesitesetup'),
    url(r'^reg-on-server/', captureapp.server_add_capture, name='reg-on-server'),
    url(r'^export/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.EXPORT_ROOT}),  
)

ovc_library/models.py
from os.path import splitext
from django.db import models
from time import time


def get_extention(filename):
    ext = splitext(filename)[1][1:].lower()
    return ext


def get_upload_file_name(instance, filename):
    return 'documents/%s.%s' % (str(time()).replace('.', '_'), get_extention(filename))


class Document(models.Model):
    document_id = models.AutoField(primary_key=True)
    document_title = models.CharField(max_length=255, unique=True)
    document_keywords = models.CharField(max_length=255, null=True, blank=True, )
    extension = models.CharField(max_length=4)
    geographic_relevancy_id = models.CharField(max_length=4, null=True, blank=True, )
    stage_id = models.CharField(max_length=4, null=True, blank=True, )
    stage_notes = models.CharField(max_length=255, null=True, blank=True, )
    availability_id = models.CharField(max_length=4)
    document_file = models.FileField(upload_to=get_upload_file_name)
    timestamp_created = models.DateTimeField(auto_now_add=True)
    person_id_created = models.CharField(max_length=128)
    timestamp_updated = models.DateTimeField(auto_now=True, null=True, blank=True, )
    person_id_updated = models.CharField(max_length=128, null=True, blank=True, )
    is_void = models.BooleanField(default=False)


    def __unicode__(self):
        return self.document_title

    def delete(self, *args, **kwargs):
        # You have to prepare what you need before delete the model
        storage, path = self.document_file.storage, self.document_file.path
        # Delete the model before the file
        super(Document, self).delete(*args, **kwargs)
        # Delete the file after the model
        storage.delete(path)

    class Meta:
        db_table = 'tbl_documents'


class DocumentTag(models.Model):
    document = models.ForeignKey(Document)
    tag_id = models.CharField(max_length=4)

    class Meta:
        db_table = 'tbl_documents_tags'
        unique_together = ('document', 'tag_id',)


class DocumentGeo(models.Model):
    document = models.ForeignKey(Document)
    area_id = models.IntegerField()

    class Meta:
        db_table = 'tbl_documents_geo'
        unique_together = ('document', 'area_id',)


class DocumentOrgUnit(models.Model):
    document = models.ForeignKey(Document)
    document_role_id = models.CharField(max_length=4)
    # TODO DocumentOrgUnit - confirm field type
    org_unit_id = models.IntegerField(null=True, blank=True, )
    source_name = models.CharField(max_length=255, null=True, blank=True, )

    class Meta:
        db_table = 'tbl_documents_orgs'

ovc_main/views/dashboard_views.py
import json
from django.http import HttpResponse
from ovc_main.reporting import reports_common
from django.shortcuts import render, redirect

def report_counts(request):
    dashsummary = reports_common.dashboard_reg_summary()
    return  HttpResponse(json.dumps(dashsummary))

def dashboard_children(request):
    dashsummary = reports_common.dashboard_children_section()
    return  HttpResponse(json.dumps(dashsummary))

def test(request):
    print 'test post in test multifield'
    if request.POST:
        print request.POST
    return render(request, 'ovc_main/utils_temps/multifieldpost.html')

ovc_main/views/service_views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
import datetime
import json
from ovc_main.forms.forms_helper import search_basic_service_referral_records, \
    delete_service_referral_record, get_service_records_by_form_id
from ovc_main.forms.services import basic_service_referral, residential_institution_form,\
    workforce_training_form, public_sensitisation_form
    
from ovc_main.utils import fields_list_provider, workforce_utils

from django.contrib.auth.decorators import login_required


def basic_service_referral_vw(request):
    form = basic_service_referral.BasicServiceReferralForm()
    
    return render(request, 'ovc_main/Forms/basic_service_referral_form.html', 
            {'form': form})
    
def delete_form(request):
    
    if request.POST:
        beneficiaryid = request.POST.get('benid', None)
        formid = request.POST.get('formid', None)
        encounterid = request.POST.get('encounterid', None)
        
        if beneficiaryid and beneficiaryid.isdigit():
            beneficiaryid = int(beneficiaryid)
            
        if formid and formid.isdigit():
            formid = int(formid)
            encounterid = None
        else:
            formid = None
            encounterid = int(encounterid)
            
        delete_service_referral_record(formid, beneficiaryid, request.user, encounterid)
        
    return HttpResponse(json.dumps({'success':'success'}))    
            
            
def forms_search(request):
    
    results = ''
    
    if request.GET:
        print 'forms-search:', request.GET
        form_type = request.GET.get('formtype',None)
        what = request.GET.get('what', None)
        searchtoken = request.GET.get('token', None)
        subject = request.GET.get('subject', None)
        datetosearch = request.GET.get('dateofsearch', None)
        dateattr = request.GET.get('dateattr', None)
        form_id = request.GET.get('form_id', None)
        datetouse = None
        if datetosearch:
            try:
                datetouse = datetime.datetime.strptime(datetosearch, "%d-%B-%Y").date()
            except:
                pass
        if form_type and what and subject:
            whattosearch = {'FT3e':{
                                    'past-records':search_basic_service_referral_records,
                                    'byformid':get_service_records_by_form_id
                                    }
                            }
            #print searchtoken, request.user, subject, datetouse, dateattr
            if what == 'byformid':
                results = whattosearch[form_type][what](form_id)
            else:
                results = whattosearch[form_type][what](searchtoken, request.user, 
                                                    workforceid=subject, datefilter=datetouse, 
                                                    dateattr=dateattr)
            
    return HttpResponse(json.dumps(results))

@login_required(login_url='/')
def beneficiary_search_result(request):
    if request.method == 'GET':
        to_return = {}
        token = request.GET['search_token']
        user = request.user
        
        child_list = fields_list_provider.search_ben_ovc(token, user, person_type=None)
    
        from ovc_main.views.vw_utils import gen_vw_utils as util
        formatted_ben_list = util.format_bens_for_display(child_list)
        
        return HttpResponse(json.dumps(formatted_ben_list))
def residential_institution_vw(request):
    form = residential_institution_form.ResidentialInstitutionForm()
    
    return render(request, 'ovc_main/Forms/residential_institution.html', 
            {'form': form})

def workforce_training_vw(request):
    form = workforce_training_form.WorkforceTrainingForm()

    return render(request, 'ovc_main/Forms/workforce_training.html', 
            {'form': form})

def public_sensitisation_vw(request):
    form = public_sensitisation_form.PublicSensitisationForm()

    return render(request, 'ovc_main/Forms/public_sensitisation.html', 
            {'form': form})

ovc_main/views/upload_download_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from ovc_main.utils.capture.capture_utililty import get_upload_queue, \
    get_downloads_queue, get_initial_data, stop_download
from django.http import HttpResponse, HttpResponseRedirect
import json

'''
@glyoko 29-06-2015
This class contains all the views that are used by the capture application. These 
include starting the upload and download, loading and refreshing the admin page.
'''
@login_required(login_url='/')
def stop_download_upload(request):
    download_info = []
    if request.method == 'GET':
        task_id = request.GET['task_id']
        download_info = stop_download(task_id = task_id, return_json=True)
    return HttpResponse(json.dumps((download_info)))

@login_required(login_url='/')
def capture_admin(request):      
    initial_data = get_initial_data(task_id='')
    return render(request, 'ovc_main/capture_administration.html', initial_data)

@login_required(login_url='/')
def refresh_capture_site(request):
    print 'Refresh capture view'
    initial_data = []
    if request.method == 'GET':
        task_id = request.GET['task']
        initial_data = get_initial_data(task_id = task_id, return_json=True)
    return HttpResponse(json.dumps((initial_data)))

@login_required(login_url='/')
def start_upload(request):
    print 'Start upload'
    upload_data = []
    if request.method == 'GET':                
        from rest_client import upload
        task = upload.delay()
        
        upload_data = get_upload_queue(task.task_id, return_json=True)     
    return HttpResponse(json.dumps((upload_data)))
    
@login_required(login_url='/')
def start_download(request):
    print 'Start download'
    download_data = []
    if request.method == 'GET':
        section = request.GET['section']
        password = request.GET['password']
        username = request.user.get_username()
        params = {'section':section, 'username':username, 'password':password}
        from rest_client import download
        task = download.delay(params) 
        
        download_data = get_downloads_queue(task.task_id, return_json=True)
    return HttpResponse(json.dumps((download_data)))

ovc_main/templates/ovc_main/Forms/basic_service_referral_form.html
{% extends "main_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_title %}{{ app_name }} | Basic service/referral form {% endblock %}
{% block navbar_class_dashboard %}{% endblock %}
{% block navbar_class_registries %}{% endblock %}
{% block navbar_class_workforce %}{% endblock %}

{% block body_page_title %} Basic service/referral form{% endblock %}
{% block breadcrum %}
<li class="hidden"><a href="#">Basic service/referral form</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
                    <li>Basic service/referral form</li>
{% endblock breadcrum %}

{% block content %}
	{% crispy form %}
{% endblock %}

{% block scripts %}

<script src="{% static "ovc_main/js/vendor/jquery.quicksearch.js" %}"></script>
<script src="{% static "ovc_main/js/general/multiselect-searchable.js" %}"></script>
<script src="{% static "ovc_main/js/forms_general.js" %}"></script>

<script src="{% static "ovc_main/js/basic_service_referral.js" %}"></script>
<script src="{% static "ovc_main/js/general/combobox-autocomplete-widget.js" %}"></script>
<script>

	workforce_orgs = {{workforce_orgs|safe}};

</script>
{% endblock %}

ovc_main/templates/ovc_main/Forms/test_temp.html
{% load crispy_forms_field %}
<div {% if div.css_id %}id="{{ div.css_id }}"{% endif %} 
    {% if div.css_class %}class="{{ div.css_class }}"{% endif %} {{ div.flat_attrs|safe }}>
       {% for field in div.custom_fields %}
       	{{field.label}}<p>
       {% endfor %}
</div>

ovc_main/templates/ovc_main/Forms/workforce_training.html
{% extends "main_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_title %}{{ app_name }} | Workforce training form {% endblock %}
{% block navbar_class_dashboard %}{% endblock %}
{% block navbar_class_registries %}{% endblock %}
{% block navbar_class_workforce %}{% endblock %}

{% block body_page_title %} Workforce training form {% endblock %}
{% block breadcrum %}
<li class="hidden"><a href="#"> Workforce training form </a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
<li> Workforce training form </li>
{% endblock breadcrum %}

{% block content %}
{% crispy form %}
{% endblock %}

{% block scripts %}
<script src="{% static "ovc_main/js/vendor/jquery.quicksearch.js" %}"></script>
<script src="{% static "ovc_main/js/forms_general.js" %}"></script>
<script src="{% static "ovc_main/js/general/multiselect-searchable.js" %}"></script>
<script src="{% static "ovc_main/js/workforce_training.js" %}"></script>
<script>

$('.datepicker').datepicker(
        {
            //minDate: "-18Y",
            dateFormat: 'd-MM-yy',
            yearRange: "1904:2050",
            maxDate: 0,
            changeMonth: true,
            changeYear: true
        });

		function duplicateOrgsDetected(org_unit_id){
			var count = 0;
			var toReturn = false;
			$("#valid_orgs_data").text("");
			$("#valid_orgs_data").css('display','None');
			$("#organisationContributionTable tr").each(function(i, v){
				$(this).children('td').each(function(ii, vv){
					if($(this).attr("id") == 'org_unit_id'){
						if($(this).text() == org_unit_id){
							count++;
						}
						if(count>=1){
							toReturn = true;
						}
					}													
				});
			});
			return toReturn;
		}

		function addOrgData() {
			var org_unit_name = $("#id_org_unit_name").val();
			var org_unit_id = $("#id_org_unit_id").val();
			//var org_contribution_id = $("#id_org_contribution_id").val();
			var cont_count = 0;
			var org_contribution = $("input[name=organisation_contribution]:checked").map(function() {
				return $(this).closest('label').text();
			}).get().join(" - ")
			var org_contribution_id = $("input[name=organisation_contribution]:checked").map(function() {
				cont_count = cont_count + 1;
				return this.value;
			}).get().join(" - ")

			$("#valid_orgs_data").text("");
			$("#valid_orgs_data").css('display', 'None');

			if(duplicateOrgsDetected(org_unit_id)){
				$("#valid_orgs_data").text('This organisation unit has already been added');
				$("#valid_orgs_data").show();
				return;
			}

			if(org_unit_id === ''){
				$("#valid_orgs_data").text('Please select an organisation unit by typing in the "Organisation unit" textbox');
				$("#valid_orgs_data").show();
				return;
			}

			if(cont_count === 0){
				$("#valid_orgs_data").text('Please select atleast one contribution');
				$("#valid_orgs_data").show();
				return;
			}

			populateOrgRow(org_unit_name, org_unit_id, org_contribution_id, org_contribution);

			updateOrgStatusData();
			clearOrgForm();
		}

		//Called on load or refresh
		populateOrgTable();
		function populateOrgTable() {
			var org_data = $("#id_org_contributions_data").val();
			if (org_data === '') {
				return;
			}
			var org_data_items = JSON.parse(org_data);
			$.each(org_data_items, function (index) {
				var org_unit_name = org_data_items[index].org_unit_name;
				var org_unit_id = org_data_items[index].org_unit_id;
				var org_contribution_id = org_data_items[index].org_contribution_id;
				var org_contribution = org_data_items[index].org_contribution;

				populateOrgRow(org_unit_name, org_unit_id, org_contribution_id, org_contribution);
			});
		}

		function populateOrgRow(org_unit_name, org_unit_id, org_contribution_id, org_contribution) {

			$("#organisationContributionTable").find('tbody')
					.append($('<tr>')
							.append($('<td id="org_unit_name" class="orgdata">')
									.append($('<label>')
											.text(org_unit_name)
											)
									)
							.append($('<td id="org_unit_id" class="orgdata">')
									.append($('<label>')
											.text(org_unit_id)
											)
									)
							.append($('<td id="org_contribution" class="not_saving">')
									.append($('<label>')
											.text(org_contribution)
											)
									)
							.append($('<td id="org_contribution_id" class="orgdata">')
									.append($('<label>')
											.text(org_contribution_id)
											)
											.css('display', 'None')
											.css('width', '1%')
									)
							.append($("<td class='not_saving'> <button onclick='removeOrgRow()' class='removebutton'><i class='fa fa-trash fa-2'></i></button></td>"))
							);
		}

		function removeOrgRow() {
			$(document).on('click', 'button.removebutton', function () {
				$(this).closest('tr').remove();
				updateOrgStatusData();
				return false;
			});
		}

		function updateOrgStatusData() {
			var data = getTableDataAsJsonString('organisationContributionTable');
			$("#id_org_contributions_data").val(data);
		}

		function clearOrgForm() {
			$('#id_organisational_unit').val('');
			$('#id_org_unit_id').val('');
			$('#id_org_unit_name').val('');
			$( 'input[id="id_organisation_contribution_1"]').iCheck('uncheck');
            $( 'input[id="id_organisation_contribution_2"]').iCheck('uncheck'); 
			$( 'input[id="id_organisation_contribution_3"]').iCheck('uncheck');
            $( 'input[id="id_organisation_contribution_4"]').iCheck('uncheck'); 
			$( 'input[id="id_organisation_contribution_5"]').iCheck('uncheck');
		}

		function duplicateWfcsDetected(workforce_member_id, workforce_member_nrc){
			var count = 0;
			var toReturn = false;
			$("#valid_orgs_data").text("");
			$("#valid_orgs_data").css('display','None');
			$("#organisationContributionTable tr").each(function(i, v){
				$(this).children('td').each(function(ii, vv){
					if($(this).attr("id") == 'workforce_id' || $(this).attr("id") == 'workforce_nrc'){
						if($(this).text() !== ''){
							if($(this).text() !== workforce_member_id || $(this).text() !== workforce_member_nrc){
								count++;
							}
						}
						if(count>=1){
							toReturn = true;
						}
					}													
				});
			});
			return toReturn;
		}

		function addWorkforceData() {
			var workforce_member_id = $("#id_workforce_member_id").val();
			var workforce_member_nrc = $("#id_workforce_member_nrc").val();
			var workforce_member_name = $("#id_workforce_member_name").val();
			var participation_level = $("#id_participation_level option:selected").text();
			var participation_level_id = $("#id_participation_level").val();
			
		    $("#valid_workforce_data").text("");
			$("#valid_workforce_data").css('display', 'None');

			if(duplicateWfcsDetected(workforce_member_id, workforce_member_nrc)){
				$("#valid_orgs_data").text('This organisation unit has already been added');
				$("#valid_orgs_data").show();
				return;
			}

			if(workforce_member_id === ''){
				$("#valid_workforce_data").text('Please select a workforce member by typing in the "Workforce member" textbox');
				$("#valid_workforce_data").show();
				return;
			}

			if(participation_level_id === ''){
				$("#valid_workforce_data").text('Please select the participation level');
				$("#valid_workforce_data").show();
				return;
			}

			populateWfcRow(workforce_member_id, workforce_member_nrc, workforce_member_name, participation_level, participation_level_id);

			updateWfcStatusData();
			clearWfcForm();
		}

		//Called on load or refresh
		populateWfcTable();
		function populateWfcTable() {
			var wfc_data = $("#id_workforce_member_data").val();
			if (wfc_data === '') {
				return;
			}
			var wfc_data_items = JSON.parse(wfc_data);
			$.each(wfc_data_items, function (index) {
				var workforce_member_id = wfc_data_items[index].workforce_id;
				var workforce_member_nrc = wfc_data_items[index].workforce_nrc;
				var workforce_member_name = wfc_data_items[index].workforce_name;
				var participation_level = wfc_data_items[index].participation_level;
				var participation_level_id = wfc_data_items[index].participation_level_id;

				populateWfcRow(workforce_member_id, workforce_member_nrc, workforce_member_name, participation_level, participation_level_id);
			});
		}

		function populateWfcRow(workforce_member_id, workforce_member_nrc, workforce_member_name, participation_level, participation_level_id) {

			$("#workforceContributionTable").find('tbody')
					.append($('<tr>')
							.append($('<td id="workforce_id" class="wfcdata">')
									.append($('<label>')
											.text(workforce_member_id)
											)
									)
							.append($('<td id="workforce_nrc" class="wfcdata">')
									.append($('<label>')
											.text(workforce_member_nrc)
											)
									)
							.append($('<td id="workforce_name" class="not_saving">')
									.append($('<label>')
											.text(workforce_member_name)
											)
									)
							.append($('<td id="participation_level" class="not_saving">')
									.append($('<label>')
											.text(participation_level)
											)
									)
							.append($('<td id="participation_level_id" class="wfcdata">')
									.append($('<label>')
											.text(participation_level_id)
											)
											.css('display', 'None')
											.css('width', '1%')
									)
							.append($("<td class='not_saving'> <button onclick='removeWfcRow()' class='removebutton'><i class='fa fa-trash fa-2'></i></button></td>"))
							);
		}

		function removeWfcRow() {
			$(document).on('click', 'button.removebutton', function () {
				$(this).closest('tr').remove();
				updateWfcStatusData();
				return false;
			});
		}

		function updateWfcStatusData() {
			var data = getTableDataAsJsonString('workforceContributionTable');
			$("#id_workforce_member_data").val(data);
		}

		function clearWfcForm() {
			$('#id_workforce_member').val('');
			$('#id_workforce_member_id').val('');
			$('#id_workforce_member_nrc').val('');
			$('#id_workforce_member_name').val('');
			$('#id_participation_level').val('');
		}

		function getTableDataAsJsonString(table_name, startindex) {
			var data = {};
			var sindex = startindex ? startindex : 1;
			$("#" + table_name + " tr").each(function (i, v) {
				if (i < sindex) {
					return;
				}
				data[i] = {};
				$(this).children('td').each(function (ii, vv) {
					data[i][this.id] = $(this).text();
				});
			});
			return JSON.stringify(data);
		}
	

</script>
{% endblock %}