OVC_IMS/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ovc_main.views import dashboard_views
from rapidsms.backends.kannel.views import KannelBackendView
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'ovc_home.views.ovc_login', name='ovc_login'),
    url(r'^change_password/', 'ovc_home.views.change_password', name='change_password'),
    url(r'^logout/', 'ovc_home.views.ovc_logout', name='ovc_logout'),
    url(r'^allocate_role/', 'ovc_home.views.allocate_role', name='allocate_role'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^home/', include('ovc_home.urls')),
    url(r'^organisation/', include('ovc_main.urls')),
    url(r'^workforce/', include('ovc_main.urls')),
    url(r'^beneficiary/', include('ovc_main.urls')),
    url(r'^capture/', include('ovc_main.urls')),
    url(r'^api/', include('ovc_main.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', dashboard_views.report_counts, name='report_counts'),
    url(r'^dashboard_children/', dashboard_views.dashboard_children, name='dashboard_children'),
    url(r'^test/', dashboard_views.test, name='test'),
    #intervention, activities, service, forms
    url(r'^forms/', include('ovc_main.urls')),
    url(r'^reports/', include('ovc_main.urls')),
    #RapidSMS
    url(r'^sms/', include('ovc_sms.urls')),
    url(r'^library/', include('ovc_library.urls')),
    url(r'^kannel/', KannelBackendView.as_view(backend_name="airtel")),

)

ovc_main/urls.py
'''
Created on Sep 2, 2014

@author: MLumpa
'''
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from ovc_main.views import reg_views as views, \
    service_views, api_views as api, \
    upload_download_views as capture_views, \
    captureapp
from OVC_IMS import settings

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^new/', views.new_organisation, name='new-organisation'),
    url(r'^wards/', views.listofwards, name='listofwards'),
    url(r'^orglists/', views.org_search_results, name='org_search_results'),
    url(r'^view_org/', views.organisation_view, name='organisation_view'),
    url(r'^update_org/', views.update_organisation, name='organisation_update'),
    url(r'^wfcsearch/', views.workforce_index, name='wfc_search_index'),
    url(r'^wfclists/', views.wfc_search_results, name='wfc_search_index'),
    url(r'^get_workforce_for_res_institution/', views.get_workforce_for_res_institution, name='get_workforce_for_res_institution'),
    url(r'^new_workforce/', views.new_workforce, name='workforce'),
    url(r'^orgautocomp/', views.org_autocompletion_list, name='orgautocomplete'),
    url(r'^res_wfc_autocomplete/', views.res_wfc_autocomplete, name='res_institute_wfc_autocomplete'),
    url(r'^workforce_training_autocomplete/', views.all_workforce_autocomplete, name='workforce_training_autocomplete'),
    url(r'^res_child_autocomplete/', views.res_child_autocomplete, name='res_child_autocomplete'), 
    url(r'^public_sens_ben_autocomp/', views.public_sens_ben_autocomp, name='public_sens_ben_autocomp'),      
    url(r'^view_wfc/', views.workforce_view, name='workforce_view'),
    url(r'^update_wfc/', views.workforce_update, name='workforce_update'),
    url(r'^communities/', views.list_of_cwacs_in_ward, name='list_of_cwacs_in_ward'),
    url(r'^ben_search/', views.search_beneficiary, name='ben_search'),
    url(r'^guardian/', views.new_guardian_reg, name='guardian'),
    url(r'^child/', views.new_child_reg, name='child'),
    url(r'^ben_autocomplete/', views.ben_autocompletion_list, name='benautocomplete'),
    url(r'^ben_wfc_autocomplete/', views.ben_wfc_autocompletion_list, name='benwfcautocomplete'),
    url(r'^ben_res_autocomplete/', views.ben_res_autocompletion_list, name='benresautocomplete'),
    url(r'^benlists/', views.ben_search_results, name='ben_search_results'),
    url(r'^formlists/', views.form_search_results, name='form_search_results'),
    url(r'^view_ben/', views.beneficiary_view, name='beneficiary_view'),
    url(r'^update_ben/', views.update_beneficiary, name='beneficiary_update'),
    url(r'^guardian_contact/', views.get_guardian_contacts, name='guard_contact'),
    url(r'^capture_admin/', capture_views.capture_admin, name='capture_administration'),
    url(r'^begin_upload/', capture_views.start_upload, name='start_upload'),
    url(r'^begin_download/', capture_views.start_download, name='start_download'),
    url(r'^stop_download_upload/', capture_views.stop_download_upload, name='stop_download_upload'),
    url(r'^upload/', api.process_upload, name='api_capture_upload'),
    url(r'^download/', api.download, name='download_sections'),
    #url(r'^data_dictionary/', api.data_dictionary, name='data_dictionary'),
    url(r'^check_names/', views.check_person_names, name='check_names'),
    url(r'^check_form_titles/', views.check_form_titles, name='check_form_titles'),
    url(r'^refresh_capture_site/', capture_views.refresh_capture_site, name='refresh_capture_site'),
    url(r'^forms_home/', views.forms_home_page, name='forms_home'),
    url(r'^subject/', views.get_subject, name='subject'),
    url(r'^add_form/', views.load_form, name='add_form'),
    #url(r'^user_can_add_form/', views.user_can_add_form, name='user_can_add_form'),
    url(r'^get_wfc_object/', views.get_wfc, name='get_wfc_object'),
    url(r'^delete/', views.delete_form, name='delete'),
    url(r'^reports_and_analysis/', views.reports_and_analysis, name='reports_and_analysis'),
    url(r'^rep_utils/', views.report_utils, name='rep_utils'),
    url(r'^report_params/', views.report_paramenters, name='report_params'),
    url(r'^run_report/', views.get_report, name='run_report'),
    #url(r'^persons/', views.get_persons_list, name='api_persons_list'),
    url(r'^get_reported_by_options/', views.get_reported_by_options, name='get_field_options'),
    url(r'^help/', views.view_help, name='help'),
    url(r'^form-search/', service_views.forms_search, name='form_search'),
    url(r'^delrecord/', service_views.delete_form, name='delete_form'),
    #url(r'^help/', TemplateView.as_view(template_name='ovc_main/ZOMIS_help_html/HTML/index.html')),
    
    url(r'^basic_service_referral/', service_views.basic_service_referral_vw, name='basic_service_referral'),
    url(r'^residential_institution/', service_views.residential_institution_vw, name='residential_institution'),
    url(r'^workforce_training/', service_views.workforce_training_vw, name='workforce_training'),
    url(r'^public_sensitisation/', service_views.public_sensitisation_vw, name='public_sensitisation'),
    url(r'^all_ben_autocomplete/', service_views.beneficiary_search_result, name='beneficiary_search_result'),
    
    url(r'^initialsitesetup/', captureapp.setup_capture_site, name='capturesitesetup'),
    url(r'^reg-on-server/', captureapp.server_add_capture, name='reg-on-server'),
    url(r'^export/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.EXPORT_ROOT}),  
)

ovc_auth/models.py
from django.db import models
from django.utils import timezone
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
#from ovc_main.models import RegPerson
from django.contrib.auth.models import BaseUserManager,AbstractBaseUser, PermissionsMixin, Group, Permission

from datetime import datetime
from django.db.models.fields.related import RelatedField



  
class OVCUserManager(BaseUserManager):

    def _create_user(self, workforce_id, password,
                     is_staff, is_superuser, **extra_fields):
        now = datetime.now()
        if not workforce_id:
            raise ValueError('The given workforce ID must be set')

        user = self.model(workforce_id=workforce_id,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, workforce_id, password=None, **extra_fields):
        return self._create_user(workforce_id, password, False, False,
                                 **extra_fields)

    def create_superuser(self, workforce_id, password, **extra_fields):
        return self._create_user(workforce_id, password, True, True,
                                 **extra_fields)

class AppUser(AbstractBaseUser, PermissionsMixin):
    
    reg_person = models.ForeignKey('ovc_main.RegPerson', null=True)
    workforce_id = models.CharField(max_length=8, unique=True)
    national_id = models.CharField(max_length=15, null=True, blank=True)
    
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    designated_phone_number = models.CharField(max_length=50, blank = True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    
    date_joined = models.DateTimeField(auto_now_add=True)
    
    timestamp_created = models.DateTimeField(auto_now_add=True)
    timestamp_updated = models.DateTimeField(auto_now=True)
    
    password_changed_timestamp = models.DateTimeField(null=True)
    
    objects = OVCUserManager()
    
    USERNAME_FIELD = 'workforce_id'
    REQUIRED_FIELDS = []
    
    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'
        db_table = 'auth_user'
        
    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name
    
    def get_username(self):
        if self.national_id:
            return self.national_id
        elif self.workforce_id:
            return self.workforce_id
        else:
            return None
    
    
    
    
class OVCPermission(Permission):
    permission_description = models.CharField(max_length=255)
    permission_set = models.CharField(max_length=100)
    permission_type = models.CharField(max_length=50, blank=True)
    restricted_to_self = models.BooleanField(blank=True, default=False)
    restricted_to_org_unit = models.BooleanField(blank=True, default=False)
    restricted_to_geo = models.BooleanField(blank=True, default=False)
    timestamp_modified = models.DateTimeField(auto_now=True, default=datetime.now())
    
    class Meta:
        db_table = 'auth_permission_detail'

class OVCRole(Group):
    group_id = models.CharField(max_length=5)
    group_name = models.CharField(max_length=100)
    group_description = models.CharField(max_length=255)
    restricted_to_org_unit = models.BooleanField(blank=True, default=False)
    restricted_to_geo  = models.BooleanField(blank=True,default=False)
    automatic  = models.BooleanField(default=False)
    timestamp_modified = models.DateTimeField(auto_now=True, default=datetime.now())
    class Meta:
        db_table = 'auth_group_detail'
    
class OVCUserRoleGeoOrg(models.Model):
    from ovc_main.models import RegPersonsGeo, RegOrgUnit
    user = models.ForeignKey(AppUser)
    group = models.ForeignKey(OVCRole)
    org_unit = models.ForeignKey(RegOrgUnit, null=True)
    area = models.ForeignKey(RegPersonsGeo, null=True)
    timestamp_modified = models.DateTimeField(auto_now=True, default=datetime.now())
    void = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'auth_user_groups_geo_org'
    
    
    
    
    

ovc_main/models/audit_trail.py
from django.db import models
from ovc_main.models import RegOrgUnit, RegPerson

class RegOrgUnitsAuditTrail(models.Model):
    from ovc_auth.models import AppUser
    transaction_id = models.AutoField(primary_key=True)
    org_unit = models.ForeignKey(RegOrgUnit)
    transaction_type_id = models.CharField(max_length=4, null=True, db_index=True)
    interface_id = models.CharField(max_length=4, null=True, db_index=True)
    timestamp_modified = models.DateTimeField(auto_now=True)
    app_user = models.ForeignKey(AppUser, db_column = 'user_id_modified')

    class Meta:
        db_table = 'tbl_reg_org_units_audit_trail'
        app_label = 'ovc_main'


class RegPersonsAuditTrail(models.Model):
    from ovc_auth.models import AppUser
    transaction_id = models.AutoField(primary_key=True)
    person = models.ForeignKey(RegPerson)
    transaction_type_id = models.CharField(max_length=4, null=True, db_index=True)
    interface_id = models.CharField(max_length=4, null=True, db_index=True)
    date_recorded_paper = models.DateField(null=True)
    person_id_recorded_paper = models.IntegerField(max_length=4, null=True)
    timestamp_modified  = models.DateTimeField(auto_now=True)
    app_user = models.ForeignKey(AppUser, db_column = 'user_id_modified')

    class Meta:
        db_table = 'tbl_reg_persons_audit_trail'
        app_label = 'ovc_main'

ovc_main/views/dashboard_views.py
import json
from django.http import HttpResponse
from ovc_main.reporting import reports_common
from django.shortcuts import render, redirect

def report_counts(request):
    dashsummary = reports_common.dashboard_reg_summary()
    return  HttpResponse(json.dumps(dashsummary))

def dashboard_children(request):
    dashsummary = reports_common.dashboard_children_section()
    return  HttpResponse(json.dumps(dashsummary))

def test(request):
    print 'test post in test multifield'
    if request.POST:
        print request.POST
    return render(request, 'ovc_main/utils_temps/multifieldpost.html')

ovc_main/views/service_views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
import datetime
import json
from ovc_main.forms.forms_helper import search_basic_service_referral_records, \
    delete_service_referral_record, get_service_records_by_form_id
from ovc_main.forms.services import basic_service_referral, residential_institution_form,\
    workforce_training_form, public_sensitisation_form
    
from ovc_main.utils import fields_list_provider, workforce_utils

from django.contrib.auth.decorators import login_required


def basic_service_referral_vw(request):
    form = basic_service_referral.BasicServiceReferralForm()
    
    return render(request, 'ovc_main/Forms/basic_service_referral_form.html', 
            {'form': form})
    
def delete_form(request):
    
    if request.POST:
        beneficiaryid = request.POST.get('benid', None)
        formid = request.POST.get('formid', None)
        encounterid = request.POST.get('encounterid', None)
        
        if beneficiaryid and beneficiaryid.isdigit():
            beneficiaryid = int(beneficiaryid)
            
        if formid and formid.isdigit():
            formid = int(formid)
            encounterid = None
        else:
            formid = None
            encounterid = int(encounterid)
            
        delete_service_referral_record(formid, beneficiaryid, request.user, encounterid)
        
    return HttpResponse(json.dumps({'success':'success'}))    
            
            
def forms_search(request):
    
    results = ''
    
    if request.GET:
        print 'forms-search:', request.GET
        form_type = request.GET.get('formtype',None)
        what = request.GET.get('what', None)
        searchtoken = request.GET.get('token', None)
        subject = request.GET.get('subject', None)
        datetosearch = request.GET.get('dateofsearch', None)
        dateattr = request.GET.get('dateattr', None)
        form_id = request.GET.get('form_id', None)
        datetouse = None
        if datetosearch:
            try:
                datetouse = datetime.datetime.strptime(datetosearch, "%d-%B-%Y").date()
            except:
                pass
        if form_type and what and subject:
            whattosearch = {'FT3e':{
                                    'past-records':search_basic_service_referral_records,
                                    'byformid':get_service_records_by_form_id
                                    }
                            }
            #print searchtoken, request.user, subject, datetouse, dateattr
            if what == 'byformid':
                results = whattosearch[form_type][what](form_id)
            else:
                results = whattosearch[form_type][what](searchtoken, request.user, 
                                                    workforceid=subject, datefilter=datetouse, 
                                                    dateattr=dateattr)
            
    return HttpResponse(json.dumps(results))

@login_required(login_url='/')
def beneficiary_search_result(request):
    if request.method == 'GET':
        to_return = {}
        token = request.GET['search_token']
        user = request.user
        
        child_list = fields_list_provider.search_ben_ovc(token, user, person_type=None)
    
        from ovc_main.views.vw_utils import gen_vw_utils as util
        formatted_ben_list = util.format_bens_for_display(child_list)
        
        return HttpResponse(json.dumps(formatted_ben_list))
def residential_institution_vw(request):
    form = residential_institution_form.ResidentialInstitutionForm()
    
    return render(request, 'ovc_main/Forms/residential_institution.html', 
            {'form': form})

def workforce_training_vw(request):
    form = workforce_training_form.WorkforceTrainingForm()

    return render(request, 'ovc_main/Forms/workforce_training.html', 
            {'form': form})

def public_sensitisation_vw(request):
    form = public_sensitisation_form.PublicSensitisationForm()

    return render(request, 'ovc_main/Forms/public_sensitisation.html', 
            {'form': form})

ovc_main/templates/ovc_main/custom_date_field.html
{% load crispy_forms_field %}

<div class="col-md-5">
	<div class="col-md-6">
		{%if form.is_update_page %}
		<label style="{{field_style}}">Location change date:</label>
		{% endif %}
	</div>
	<div class="col-md-5">
		{% crispy_field field %}
	</div>
	<div class="col-md-11">
	{% if form_show_errors and field.errors %}
	    {% for error in field.errors %}
	        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="error-block" style="color:#BB4442"><strong>{{ error }}</strong></span>
	    {% endfor %}
	{% endif %}
	</div>
</div>

ovc_main/templates/ovc_main/custom_duration_control.html
{% load crispy_forms_field %}
<div class="col-md-3">
	<label for="id_duration_of_training" class="control-label col-md-12 requiredField">
					Duration of event:<span class="asteriskField">*</span></label>
</div>
<div class="col-md-3">
	{% crispy_field field %}
</div>

ovc_main/templates/ovc_main/custom_guardian_change_date.html
{% load crispy_forms_field %}

<div class="col-md-5">
	<div class="col-md-6">
		{%if form.is_update_page %}
		<label style="{{field_style}}">Guardian change date:</label>
		{% endif %}
	</div>
	<div class="col-md-5">
		{% crispy_field field %}
	</div>
	<div class="col-md-11">
	{% if form_show_errors and field.errors %}
	    {% for error in field.errors %}
	        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="error-block" style="color:#BB4442"><strong>{{ error }}</strong></span>
	    {% endfor %}
	{% endif %}
	</div>
</div>

ovc_main/templates/ovc_main/custom_workforce_type_date.html
{% load crispy_forms_field %}

<div class="col-md-7">
	<div class="col-md-6">
		{%if form.is_update_page %}
		<label style="{{field_style}}">Workforce/user type change date: </label>
		{% endif %}
	</div>
	<div class="col-md-5">
		{% crispy_field field %}
	</div>
	<div class="col-md-11">
	{% if form_show_errors and field.errors %}
	    {% for error in field.errors %}
	        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="error-block" style="color:#BB4442;font-size: 14px"><strong>{{ error }}</strong></span>
	    {% endfor %}
	{% endif %}
	</div>
</div>

ovc_main/templates/ovc_main/guardian_view_readonly.html
{% extends "main_base.html" %}
{% load crispy_forms_tags %}
{% block page_title %}{{ app_name }} | Guardian {% endblock %}
{% block navbar_class_dashboard %}{% endblock %}
{% block navbar_class_registries %}active{% endblock %}
{% block navbar_class_beneficiary %}active{% endblock %}

{% block body_page_title %} View details - guardian{% endblock %}
{% block breadcrum %}
<li class="hidden"><a href="#">Guardian - view details</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
                    <li>Guardian - view details</li>
{% endblock breadcrum %}
{% block content %}
	<div class="form-horizontal">
		<div class="note note-info">
			<h4><strong>Guardian - view details</strong></h4>
		</div></p>
		
		<div class="multiField">
			<div class="panel panel-primary" >
				<div class="panel-body pan" ><p/> 
				<div id="div_id_zomis_id" class="form-group">
						<label for="id_zomis_id" class="control-label col-md-3">ZOMIS beneficiary ID</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.beneficiary_id}}</strong></p>
					    </div>
						
					</div>
					
					<div id="div_id_national_id" class="form-group">
						<label for="id_national_id" class="control-label col-md-3">NRC number</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{ beneficiary.national_id }}</strong></p>
					    </div>
					</div>
				</div>
			</div>
					
			<div class="panel panel-primary" >
				<div class="panel-heading" >
		       		Guardian personal details
				</div>
				<div class="panel-body pan" ><p/> 
					 <div id="div_id_first_name" class="form-group">
						<label for="id_first_name" class="control-label col-md-3">First name</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.first_name}}</strong></p>
					</div>
						
					</div>
					<div id="div_id_last_name" class="form-group">
						<label for="id_last_name" class="control-label col-md-3">Surname</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.last_name}}</strong></p>
					    </div>
					</div>
					
					<div id="div_id_other_name" class="form-group">
						<label for="id_other_name" class="control-label col-md-3">Other name(s)</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.other_name}}</strong></p>
					    </div>
					</div>
					
					<div id="div_id_sex" class="form-group">
						<label for="id_sex" class="control-label col-md-3">Sex</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.sex}}</strong></p>
					    </div>
					</div>
					
					<div id="div_id_date_of_birth" class="form-group">
						<label for="id_date_of_birth" class="control-label col-md-3">Date of birth</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.date_of_birth|date:"d M Y"}}</strong></p>
					    </div>
					</div>
					
				</div>
			</div>
			
			<div class="panel panel-primary" >
				<div class="panel-heading" >
				       Where the guardian lives
				</div>
				
				<div class="panel-body pan" ><p/> 
										
					<div id="div_id_district" class="form-group">
						<label for="id_district" class="control-label col-md-3">
								District</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.residence.district}}</strong></p>
					    </div>
					</div>
					
					<div id="div_id_ward" class="form-group">
						<label for="id_ward" class="control-label col-md-3">
								Ward</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.residence.ward}}</strong></p>
					    </div>
					</div>
					
					<div id="div_id_community" class="form-group">
						<label for="id_community" class="control-label col-md-3">
								Community (CWAC or GDCLSU)</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.residence.community}}</strong></p>
					    </div>
					</div>
					
					<div id="div_id_physical_address" class="form-group">
						<label for="id_physical_address" class="control-label col-md-3">
								Physical address / description of where living</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.contact.physical_address}}</strong></p>
					    </div>
					</div>
				</div>
			</div>
						
			<div class="panel panel-primary" >
				<div class="panel-heading" >
				       Guardian's contact details
				</div>
					
					<div id="div_id_district" class="form-group">
						<label for="id_district" class="control-label col-md-3">
								Mobile number</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.contact.mobile_phone_number}}</strong></p>
					    </div>
					</div>
					
					<div id="div_id_ward" class="form-group">
						<label for="id_ward" class="control-label col-md-3">
								Email address</label>
						<div class="col-md-6">
					      <p class="form-control-static"><strong>{{beneficiary.contact.email_address}}</strong></p>
					    </div>
					</div>
				</div>
			</div>
			
			<div class="panel panel-primary" >
				<div class="panel-heading" >
				       Paper trail
				</div>
					
				<table id="paperTrailTable"  class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>Person recorded on paper</th>
                        <th>Date recorded on paper</th>
                        <th>Person recorded electronically</th>
                        <th>Date time recorded electronically</th>
                        <th>Interface</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% if beneficiary.audit_trail  %}
                        {% for audit in beneficiary.audit_trail %}
                            <tr>
                                <td id = "1">{{ audit.Person_recorded_on_paper }}</td>
                                <td id = "2">{{ audit.Paper_date }}</td>
                                <td id = "3">{{ audit.Person_recorded_electronically }}</td>
                                <td id = "4">{{ audit.Electronic_date_time }}</td>
                                <td id = "5">{{ audit.Interface }}</td>
                            </tr>
                        {% endfor %}
                        {% endif %}
                    </tbody>
                </table>
                                    
			</div>
			
	<div class="md-col-6" style="margin-left:41%">
	{% if 'auth.update ben special' in perms or 'auth.update ben contact' in perms or 'auth.update ben general' in perms or 'auth.update ben contact by org' in perms or 'auth.update ben general by org' in perms %}
			<a type="button" href="/beneficiary/update_ben?beneficiary_id={{beneficiary.pk_id}}" class="btn btn-primary"><i class="fa fa-pencil-square-o"></i> Update...</a>
	{% endif %}
		<a type="button" href="/beneficiary/ben_search/" class="btn btn-success"><i class="fa fa-arrow-circle-o-left"></i> Go Back</a>
	</div>
</div>
{% endblock content %}

ovc_main/templates/ovc_main/new_organisation.html
{% extends "main_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_title %}{{ app_name }} | Organisational unit {% endblock %}
{% block navbar_class_dashboard %}{% endblock %}
{% block navbar_class_registries %}active{% endblock %}
{% block navbar_class_org_unit %}active{% endblock %}

{% block body_page_title %} <i class="fa fa-plus fa-6"></i> {{page_title}} {% endblock %}
{% block breadcrum %}
<li class="hidden"><a href="#">Organisational unit</a>&nbsp;&nbsp;<i class="fa fa-angle-right"></i>&nbsp;&nbsp;</li>
                    <li>Organisational unit</li>
{% endblock breadcrum %}

{% block content %}
<div class="container">
    <div class="row">

		{% crispy form %}
	</div>
</div>
<!--script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script-->
<script src="{% static "themeforest_uadmin/js/jquery-1.10.2.min.js" %}"></script>
<script src="{% static "themeforest_uadmin/vendors/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.js" %}"></script>

<script>
$(document).ready(function() {
    $('.datepicker').datepicker({
            dateFormat: 'd-MM-yy',
            yearRange: "1904:2050",
            maxDate: 0,
            changeMonth: true,
            changeYear: true
		});

    $("input[id='orgclosedcheckbox']").on('ifChecked',function(){
    	$('.date_closed_control').show();
    	$("input[id='id_org_never_existed']").iCheck('uncheck');

    });
    $("input[id='orgclosedcheckbox']").on('ifUnchecked',function(){
    	$('.date_closed_control').hide();
    	$( "#id_date_closed" ).datepicker( "setDate","");

    });

    $("input[id='id_org_never_existed']").on('ifChecked',function(){
    	$("input[id='orgclosedcheckbox']").iCheck('uncheck');

    });

    if($("input[id='orgclosedcheckbox']").is(':checked'))
    {
    	$('.date_closed_control').show();
    }
});
</script>
{% endblock content %}

{% block scripts %}
<script src="{% static "ovc_main/js/vendor/jquery.quicksearch.js" %}"></script>
<script>
$("form").submit(function(){
    $(":submit").attr('disabled', 'disabled');
    return true;
});
</script>
{% endblock scripts %}